{
 "title": "NGINX SRE Overview",
 "tags": [
  "nginx",
  "sre"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Node CPU Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode!='idle'}[5m])"
    }
   ]
  },
  {
   "title": "NGINX Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "nginx_connections_active" }
   ]
  },
  {
   "title": "Memory Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes" }
   ]
  },
  {
   "title": "Nginx Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"hostlogs\"}"
    }
   ]
  }
 ]
}