kubernetes_apt_minor_version: "v1.34"
kubernetes_pod_network_cidr: "10.244.0.0/16"
kubernetes_cni_manifest_url: "https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml"
kubernetes_admin_user: "ubuntu"
