apiVersion: v1
kind: Namespace
metadata:
  name: infra
  labels:
    name: infra
    purpose: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: airgap
  labels:
    name: airgap
    purpose: offline-operations
