apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
type: Opaque
stringData:
  PLATFORM_TERADATA_HOST: ""
  PLATFORM_TERADATA_USER: ""
  PLATFORM_TERADATA_PASSWORD: ""
  JUPYTER_TOKEN: platform123
