- name: Install security packages
  apt:
    name:
      - ufw
      - fail2ban
    state: present

- name: Default deny incoming
  community.general.ufw:
    direction: incoming
    policy: deny

- name: Default allow outgoing
  community.general.ufw:
    direction: outgoing
    policy: allow

- name: Allow SSH
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Allow HTTP
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Allow Node Exporter
  community.general.ufw:
    rule: allow
    port: '9100'
    proto: tcp

- name: Allow Nginx Exporter
  community.general.ufw:
    rule: allow
    port: '9113'
    proto: tcp

- name: Enable UFW
  community.general.ufw:
    state: enabled

- name: Deploy fail2ban jail.local
  copy:
    dest: /etc/fail2ban/jail.local
    mode: '0644'
    content: |
      [DEFAULT]
      bantime = 10m
      findtime = 10m
      maxretry = 5
      backend = systemd

      [sshd]
      enabled = true

- name: Enable fail2ban
  service:
    name: fail2ban
    enabled: true
    state: started
